version: '3.8'
# chay thu tu ntn?
# con cai nao optional ko ta
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      co can ko?
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
#      can zoo keeper o day k
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
#      can nay ko
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - app-network

  postgresql:
    image: postgres:15
    restart: always
    command: postgres -c 'max_connections=150' -c 'shared_buffers=256MB'
    environment:
      POSTGRES_DB: gautoidb
      POSTGRES_PASSWORD: gautoi
      POSTGRES_USER: gautoi
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gautoi" ]
      interval: 10s
      timeout: 5s
      retries: 5


  demo:
    build: .
#     co can ko z
    image: ${SPRING_BOOT_APP_IMAGE:-springboot-demo:latest}
    container_name: springboot-demo
    depends_on:
      - postgresql
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/gautoidb
      - SPRING_DATASOURCE_USERNAME=gautoi
      - SPRING_DATASOURCE_PASSWORD=gautoi
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_LIQUIBASE_ENABLED=true
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:/db/changelog/db.changelog-master.xml
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: