spring.application.name=gautoi
# PostgreSQL database
spring.datasource.url=jdbc:postgresql://localhost:5432/gautoidb
spring.datasource.username=gautoi
spring.datasource.password=gautoi

# JPA configurations
spring.jpa.hibernate.ddl-auto=update 

# Liquibase configurations
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://localhost:5432/gautoidb
spring.liquibase.driver-class-name=org.postgresql.Driver
spring.liquibase.user=gautoi
spring.liquibase.password=gautoi
#kafka config
spring.kafka.bootstrap-servers=localhost:9092
#customer config
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.properties[spring.json.trusted.packages]=*
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
#retry
spring.kafka.retry.backoff=3000
spring.kafka.retry.max-attempts=4
spring.kafka.retry.concurrency=1
